name = "SciBmad"
uuid = "7bf6e793-a2ec-421f-8700-d1465381ee80"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
